default: &default
  adapter: postgresql
  host: ''
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default
  database: <%= ENV['DATABASE_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_PRODUCTION'] %>
